### ISSUE TITLE
Tabs sometimes do not update

### ISSUE THREAD

**Issue by gdalli** [Hi1ah/lucid-tech#4]
I have been having an issue where tabs stop updating after using lucid for 20+ minutes.  I have tried to catch in the debug logs why tabs aren't be deleted or changed, but when I reference the logs after replicating the error, I get the message that there are too many messages to display, so was not able to get to the bottom of this.  To solve this, I have the background app refreshing itself every 2 minutes.  The user does not notice this as when the background app is refreshed, React will not recognize a change in the UI and thus will not change anything on the screen.  This has solved the issue, but I don't think it is a great fix.  On the background.jsx file, you can see the interval function to keep this going.  

---------

Note from Hilah: 
In addition to the tabs not updating after 20 or so minutes, many changes are not reflected immediately after an action takes place (i.e. appropriately disappearing from screen after they have been trashed or saved). There seems to be a lag where the link itself will close or save if you select the action, but the link visibly still lingers on the home page until you refresh.

**Comment by Hi1ah** [comment]
This is so great! Thanks! You can finish our equal exchange chocolate bar :dancers:
